module Jekyll
  class MarkerGenerator < Generator
    safe true
    priority :lowest

    def generate(site)
      page = PageWithoutAFile.new(site, site.source, "", "marker.html")
      page.content = <<~HTML
        <html>
        <body>
          <h1>POC: Jekyll Plugin Code Execution</h1>
          <p>this file was generated by a custom Jekyll plugin from a fork PR.</p>
          <p>build time: #{Time.now.utc}</p>
          <p>Ruby version: #{RUBY_VERSION}</p>
          <p>working directory: #{Dir.pwd}</p>
          <p>environment variables available (names only, no values):</p>
          <ul>
            #{ENV.keys.sort.map { |k| "<li>#{k}</li>" }.join("\n        ")}
          </ul>
        </body>
        </html>
      HTML
      page.data["layout"] = nil
      site.pages << page
    end
  end
end