#!/usr/bin/env ruby

require "bundler/setup"
require "html-proofer"

url_ignores = [
  /github\.com\/github\/open-source-guide/, # not yet public
  'https://karissa.github.io/post/okf-de'
]

HTMLProofer::Runner.new(["_site"],
  :type => :directory,
  :url_ignore => url_ignores,
  :verbose => !!ENV["VERBOSE"],
  :check_html => true
).run
