#!/usr/bin/env node

// Retext stuff
var unified = require('unified');

// Remark stuff
var parse = require('remark-parse');
var lint = require('remark-lint');
var remark2retext = require('remark-retext');
var stringify = require('remark-stringify');

// Util stuff
var report = require('vfile-reporter');
var glob = require('glob');
var fs = require('fs');
var async = require('async');
var yaml = require('js-yaml');
var jekyllConfig = yaml.safeLoad(fs.readFileSync('_config.yml', 'utf8'));
var ignore = require('ignore')().add(jekyllConfig["exclude"])

var options = {
  // https://github.com/wooorm/remark/tree/master/packages/remark-parse#options
  "remark": {
    "gfm": true,
    "footnotes": true
  },

  // https://github.com/wooorm/remark-lint/blob/master/doc/rules.md
  "lint": {
    "list-item-indent": "space",    // As the gods intended.
    "maximum-line-length": false,   // turn off line length linting
    "no-html": false,               // Sadly, need HTML for video embeds
    "no-heading-punctuation": false,
    "list-item-spacing": false,
    "first-heading-level": 2,       // Page title is h1, so start with h2
    "emphasis-marker": "_",

    // FIXME: Eventually remove these
    "maximum-heading-length": 80,
    "no-missing-blank-lines": false,
  },
  "readability": {
    "age": 18
  },
  "simplify": {
    ignore: [
      "modify",
      "contribute",
      "previous"
    ]
  }
};

async.map(ignore.filter(glob.sync("**/*.md")), function(file, callback) {
  fs.readFile(file, function(err, contents) {
    unified()
      .use(parse)
      .use(lint, options["lint"])
      // .use(remark2retext, unified()
      //   .use(require('retext-english'))
      //   .use(require('retext-simplify'), options["simplify"])
      //   .use(require('retext-equality'))
      //   .use(require('retext-readability'), options["readability"])
      // )
      .use(stringify)
      .process(contents.toString(), options["remark"], function (err, result) {
          result.filename = file;
          callback(err, result);
      });
  });
}, function (err, results) {
  console.log(report(results));

  var hasErrors = false;

  results.forEach(function(file) {
    if(file.messages.length > 0) hasErrors = true;
  });

  if(hasErrors) process.exit(1);
});
