name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v6.4.0
      - name: Bootstrap
        run: script/bootstrap
        env:
          SKIP_BUNDLER: true
      - name: Tests
        run: script/test
